Update milestones.yml

diff --git a/.github/workflows/milestones.yml b/.github/workflows/milestones.yml
--- a/.github/workflows/milestones.yml
+++ b/.github/workflows/milestones.yml
@@ -29,9 +29,15 @@ jobs:
       id: create_milestone
       run: |
         #!/bin/bash
-        curl -X POST \
+        RESPONSE=$(curl -X POST \
           -H "User-Agent: GitHub-API-Request" \
           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/${{ github.repository }}/milestones \
-          -d "{\"title\":\"$DATE Release\", \"description\":\"$DESCRIPTION\", \"due_on\":\"$DATE_ISO8601\", \"state\":\"open\"}"
+          -d "{\"title\":\"$DATE Release\", \"description\":\"$DESCRIPTION\", \"due_on\":\"$DATE_ISO8601\", \"state\":\"open\"}")
+
+        # Check the exit status of the curl request
+        if [ $? -ne 0 ]; then
+          echo "Error: Failed to create a milestone."
+          exit 1
+        fi
